
@baseUrl= http://localhost
@port = 8080


# @name getUsers
GET {{baseUrl}}:{{port}}/api/SeeUsers

###
# @name createUser
POST {{baseUrl}}:{{port}}/api/createANewUser
Content-Type: application/json

    {
        "nombre": "Juan Pérez",
        "correo": "juan@ejemplo135.com",
        "password": "secreta1",
        "institution": "IPN",
        "address": "CDMX, calle ejemplo, número 1",
        "activo": false

    }

